// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfZKHtsHBJfG8pUMDYyBYhV3F9qC_xqos',
    appId: '1:954212027016:web:8e6e0c7f08a30c2a0b2d3d',
    messagingSenderId: '954212027016',
    projectId: 'habit-tracker-200c1',
    authDomain: 'habit-tracker-200c1.firebaseapp.com',
    storageBucket: 'habit-tracker-200c1.firebasestorage.app',
    measurementId: 'G-SYESTHFEJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhxIbco7bKAhgag5Yf8eCmLiSFEYA6Ro',
    appId: '1:954212027016:android:113bf36b1c67bdb20b2d3d',
    messagingSenderId: '954212027016',
    projectId: 'habit-tracker-200c1',
    storageBucket: 'habit-tracker-200c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9F0yqV6tIve8CE5dqMj6Nmn6yd6lh-I',
    appId: '1:954212027016:ios:6d55cf1bf9331d850b2d3d',
    messagingSenderId: '954212027016',
    projectId: 'habit-tracker-200c1',
    storageBucket: 'habit-tracker-200c1.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9F0yqV6tIve8CE5dqMj6Nmn6yd6lh-I',
    appId: '1:954212027016:ios:6d55cf1bf9331d850b2d3d',
    messagingSenderId: '954212027016',
    projectId: 'habit-tracker-200c1',
    storageBucket: 'habit-tracker-200c1.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfZKHtsHBJfG8pUMDYyBYhV3F9qC_xqos',
    appId: '1:954212027016:web:4d4da2d3c21321370b2d3d',
    messagingSenderId: '954212027016',
    projectId: 'habit-tracker-200c1',
    authDomain: 'habit-tracker-200c1.firebaseapp.com',
    storageBucket: 'habit-tracker-200c1.firebasestorage.app',
    measurementId: 'G-RFK566X5ME',
  );
}
